# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=100)),
                ('target_handle', models.CharField(max_length=15)),
                ('target_twitter_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=140)),
                ('tweet_date', models.DateTimeField(verbose_name='date tweeted')),
                ('tweet_id', models.BigIntegerField()),
                ('tweet_user_tw_id', models.BigIntegerField()),
                ('tweet_user_handle', models.CharField(max_length=15)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twittering.Target')),
            ],
        ),
    ]
